version: "3.8"
services:
  postgresql:
    image: postgres:16.2-bookworm
    container_name: billcat-postgres
    ports:
      - "5432:5432"
    networks:
      - network1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: billcat
      POSTGRES_DB: billcat
    volumes:
      # Named volumes
      - postgresql:/var/lib/postgresql/data
      # Bind mounts
      - ../billcat-sql/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgresql:
    driver: local
networks:
  network1:
    name: billcat-network
    external: false